WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
RENDER_WIDTH, RENDER_HEIGHT = 800, 600

BALL_RADIUS = 10
BALL_SPEED = 8

SHAKE_MAGNITUDE = 5
SHAKE_DURATION = 10

INITIAL_LIVES = 3

PLAYER_WIDTH_MULTIPLIER = 10

TRAIL_LENGTH = 15

FONT_SIZE = 36

TARGET_FPS = 60

# Base config
DEBUG_ENABLED_SHADERS = True
DEBUG_DISABLE_SPLASH = False
DEBUG_DISABLE_OFFSET = False
DEBUG_STARTUP_GAME = False
DEBUG_GAME_AUTOSTART = False
DEBUG_EASTER_EGG = False
DEBUG_PRECISE_MOUSE = False
DEBUG_DISABLE_ERROR_HANDLER = True
DEBUG_AUTOPLAY = False
DEBUG_INFINITE_LIVES = False

DEV_MODE = True

VERSION = "0.1.0"
RELEASE_STATE = "DEV_ALPHA"